//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/LobbyService.Web.DTO")]
    public partial class Player : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int PlayerIdField;
        
        private string PlayerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId {
            get {
                return this.PlayerIdField;
            }
            set {
                if ((this.PlayerIdField.Equals(value) != true)) {
                    this.PlayerIdField = value;
                    this.RaisePropertyChanged("PlayerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerLobby", Namespace="http://schemas.datacontract.org/2004/07/LobbyService.Web.DTO")]
    public partial class PlayerLobby : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PhoneApp1.ServiceReference1.Player HostPlayerField;
        
        private bool IsAwaitingForPlayersField;
        
        private PhoneApp1.ServiceReference1.Lobby LobbyIdField;
        
        private System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> PlayerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PhoneApp1.ServiceReference1.Player HostPlayer {
            get {
                return this.HostPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.HostPlayerField, value) != true)) {
                    this.HostPlayerField = value;
                    this.RaisePropertyChanged("HostPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAwaitingForPlayers {
            get {
                return this.IsAwaitingForPlayersField;
            }
            set {
                if ((this.IsAwaitingForPlayersField.Equals(value) != true)) {
                    this.IsAwaitingForPlayersField = value;
                    this.RaisePropertyChanged("IsAwaitingForPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PhoneApp1.ServiceReference1.Lobby LobbyId {
            get {
                return this.LobbyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyIdField, value) != true)) {
                    this.LobbyIdField = value;
                    this.RaisePropertyChanged("LobbyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lobby", Namespace="http://schemas.datacontract.org/2004/07/LobbyService.Web.DTO")]
    public partial class Lobby : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int LobbyIdField;
        
        private int LobbyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyId {
            get {
                return this.LobbyIdField;
            }
            set {
                if ((this.LobbyIdField.Equals(value) != true)) {
                    this.LobbyIdField = value;
                    this.RaisePropertyChanged("LobbyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyName {
            get {
                return this.LobbyNameField;
            }
            set {
                if ((this.LobbyNameField.Equals(value) != true)) {
                    this.LobbyNameField = value;
                    this.RaisePropertyChanged("LobbyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DoWork", ReplyAction="http://tempuri.org/IService1/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CreateLobby", ReplyAction="http://tempuri.org/IService1/CreateLobbyResponse")]
        System.IAsyncResult BeginCreateLobby(PhoneApp1.ServiceReference1.Player host, int lobby, System.AsyncCallback callback, object asyncState);
        
        void EndCreateLobby(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GatAvailablePlayLobbies", ReplyAction="http://tempuri.org/IService1/GatAvailablePlayLobbiesResponse")]
        System.IAsyncResult BeginGatAvailablePlayLobbies(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> EndGatAvailablePlayLobbies(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AddPlayer", ReplyAction="http://tempuri.org/IService1/AddPlayerResponse")]
        System.IAsyncResult BeginAddPlayer(PhoneApp1.ServiceReference1.Player pl, System.AsyncCallback callback, object asyncState);
        
        void EndAddPlayer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetPlayers", ReplyAction="http://tempuri.org/IService1/GetPlayersResponse")]
        System.IAsyncResult BeginGetPlayers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> EndGetPlayers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PhoneApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatAvailablePlayLobbiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GatAvailablePlayLobbiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PhoneApp1.ServiceReference1.IService1>, PhoneApp1.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateLobbyDelegate;
        
        private EndOperationDelegate onEndCreateLobbyDelegate;
        
        private System.Threading.SendOrPostCallback onCreateLobbyCompletedDelegate;
        
        private BeginOperationDelegate onBeginGatAvailablePlayLobbiesDelegate;
        
        private EndOperationDelegate onEndGatAvailablePlayLobbiesDelegate;
        
        private System.Threading.SendOrPostCallback onGatAvailablePlayLobbiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddPlayerDelegate;
        
        private EndOperationDelegate onEndAddPlayerDelegate;
        
        private System.Threading.SendOrPostCallback onAddPlayerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPlayersDelegate;
        
        private EndOperationDelegate onEndGetPlayersDelegate;
        
        private System.Threading.SendOrPostCallback onGetPlayersCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CreateLobbyCompleted;
        
        public event System.EventHandler<GatAvailablePlayLobbiesCompletedEventArgs> GatAvailablePlayLobbiesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddPlayerCompleted;
        
        public event System.EventHandler<GetPlayersCompletedEventArgs> GetPlayersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginCreateLobby(PhoneApp1.ServiceReference1.Player host, int lobby, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateLobby(host, lobby, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndCreateLobby(System.IAsyncResult result) {
            base.Channel.EndCreateLobby(result);
        }
        
        private System.IAsyncResult OnBeginCreateLobby(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.ServiceReference1.Player host = ((PhoneApp1.ServiceReference1.Player)(inValues[0]));
            int lobby = ((int)(inValues[1]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginCreateLobby(host, lobby, callback, asyncState);
        }
        
        private object[] OnEndCreateLobby(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndCreateLobby(result);
            return null;
        }
        
        private void OnCreateLobbyCompleted(object state) {
            if ((this.CreateLobbyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateLobbyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateLobbyAsync(PhoneApp1.ServiceReference1.Player host, int lobby) {
            this.CreateLobbyAsync(host, lobby, null);
        }
        
        public void CreateLobbyAsync(PhoneApp1.ServiceReference1.Player host, int lobby, object userState) {
            if ((this.onBeginCreateLobbyDelegate == null)) {
                this.onBeginCreateLobbyDelegate = new BeginOperationDelegate(this.OnBeginCreateLobby);
            }
            if ((this.onEndCreateLobbyDelegate == null)) {
                this.onEndCreateLobbyDelegate = new EndOperationDelegate(this.OnEndCreateLobby);
            }
            if ((this.onCreateLobbyCompletedDelegate == null)) {
                this.onCreateLobbyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateLobbyCompleted);
            }
            base.InvokeAsync(this.onBeginCreateLobbyDelegate, new object[] {
                        host,
                        lobby}, this.onEndCreateLobbyDelegate, this.onCreateLobbyCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGatAvailablePlayLobbies(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGatAvailablePlayLobbies(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> PhoneApp1.ServiceReference1.IService1.EndGatAvailablePlayLobbies(System.IAsyncResult result) {
            return base.Channel.EndGatAvailablePlayLobbies(result);
        }
        
        private System.IAsyncResult OnBeginGatAvailablePlayLobbies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGatAvailablePlayLobbies(callback, asyncState);
        }
        
        private object[] OnEndGatAvailablePlayLobbies(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGatAvailablePlayLobbies(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGatAvailablePlayLobbiesCompleted(object state) {
            if ((this.GatAvailablePlayLobbiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GatAvailablePlayLobbiesCompleted(this, new GatAvailablePlayLobbiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GatAvailablePlayLobbiesAsync() {
            this.GatAvailablePlayLobbiesAsync(null);
        }
        
        public void GatAvailablePlayLobbiesAsync(object userState) {
            if ((this.onBeginGatAvailablePlayLobbiesDelegate == null)) {
                this.onBeginGatAvailablePlayLobbiesDelegate = new BeginOperationDelegate(this.OnBeginGatAvailablePlayLobbies);
            }
            if ((this.onEndGatAvailablePlayLobbiesDelegate == null)) {
                this.onEndGatAvailablePlayLobbiesDelegate = new EndOperationDelegate(this.OnEndGatAvailablePlayLobbies);
            }
            if ((this.onGatAvailablePlayLobbiesCompletedDelegate == null)) {
                this.onGatAvailablePlayLobbiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGatAvailablePlayLobbiesCompleted);
            }
            base.InvokeAsync(this.onBeginGatAvailablePlayLobbiesDelegate, null, this.onEndGatAvailablePlayLobbiesDelegate, this.onGatAvailablePlayLobbiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginAddPlayer(PhoneApp1.ServiceReference1.Player pl, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddPlayer(pl, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PhoneApp1.ServiceReference1.IService1.EndAddPlayer(System.IAsyncResult result) {
            base.Channel.EndAddPlayer(result);
        }
        
        private System.IAsyncResult OnBeginAddPlayer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.ServiceReference1.Player pl = ((PhoneApp1.ServiceReference1.Player)(inValues[0]));
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginAddPlayer(pl, callback, asyncState);
        }
        
        private object[] OnEndAddPlayer(System.IAsyncResult result) {
            ((PhoneApp1.ServiceReference1.IService1)(this)).EndAddPlayer(result);
            return null;
        }
        
        private void OnAddPlayerCompleted(object state) {
            if ((this.AddPlayerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddPlayerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddPlayerAsync(PhoneApp1.ServiceReference1.Player pl) {
            this.AddPlayerAsync(pl, null);
        }
        
        public void AddPlayerAsync(PhoneApp1.ServiceReference1.Player pl, object userState) {
            if ((this.onBeginAddPlayerDelegate == null)) {
                this.onBeginAddPlayerDelegate = new BeginOperationDelegate(this.OnBeginAddPlayer);
            }
            if ((this.onEndAddPlayerDelegate == null)) {
                this.onEndAddPlayerDelegate = new EndOperationDelegate(this.OnEndAddPlayer);
            }
            if ((this.onAddPlayerCompletedDelegate == null)) {
                this.onAddPlayerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddPlayerCompleted);
            }
            base.InvokeAsync(this.onBeginAddPlayerDelegate, new object[] {
                        pl}, this.onEndAddPlayerDelegate, this.onAddPlayerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.ServiceReference1.IService1.BeginGetPlayers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPlayers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> PhoneApp1.ServiceReference1.IService1.EndGetPlayers(System.IAsyncResult result) {
            return base.Channel.EndGetPlayers(result);
        }
        
        private System.IAsyncResult OnBeginGetPlayers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp1.ServiceReference1.IService1)(this)).BeginGetPlayers(callback, asyncState);
        }
        
        private object[] OnEndGetPlayers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> retVal = ((PhoneApp1.ServiceReference1.IService1)(this)).EndGetPlayers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPlayersCompleted(object state) {
            if ((this.GetPlayersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPlayersCompleted(this, new GetPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPlayersAsync() {
            this.GetPlayersAsync(null);
        }
        
        public void GetPlayersAsync(object userState) {
            if ((this.onBeginGetPlayersDelegate == null)) {
                this.onBeginGetPlayersDelegate = new BeginOperationDelegate(this.OnBeginGetPlayers);
            }
            if ((this.onEndGetPlayersDelegate == null)) {
                this.onEndGetPlayersDelegate = new EndOperationDelegate(this.OnEndGetPlayers);
            }
            if ((this.onGetPlayersCompletedDelegate == null)) {
                this.onGetPlayersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPlayersCompleted);
            }
            base.InvokeAsync(this.onBeginGetPlayersDelegate, null, this.onEndGetPlayersDelegate, this.onGetPlayersCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp1.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<PhoneApp1.ServiceReference1.IService1>, PhoneApp1.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<PhoneApp1.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginCreateLobby(PhoneApp1.ServiceReference1.Player host, int lobby, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = host;
                _args[1] = lobby;
                System.IAsyncResult _result = base.BeginInvoke("CreateLobby", _args, callback, asyncState);
                return _result;
            }
            
            public void EndCreateLobby(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("CreateLobby", _args, result);
            }
            
            public System.IAsyncResult BeginGatAvailablePlayLobbies(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GatAvailablePlayLobbies", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> EndGatAvailablePlayLobbies(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.PlayerLobby>)(base.EndInvoke("GatAvailablePlayLobbies", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddPlayer(PhoneApp1.ServiceReference1.Player pl, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pl;
                System.IAsyncResult _result = base.BeginInvoke("AddPlayer", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddPlayer(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddPlayer", _args, result);
            }
            
            public System.IAsyncResult BeginGetPlayers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPlayers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> EndGetPlayers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp1.ServiceReference1.Player>)(base.EndInvoke("GetPlayers", _args, result)));
                return _result;
            }
        }
    }
}
